url: http://sundarsaravanan.github.io
baseurl: /timeline-jekyll-theme

# Site Settings
title: Sundar Saravanan
description: "Software Engineer, trader and competitive swimmer"
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
